--- # Installing webserver
- hosts: webserver
  user: test
  sudo: yes
  tasks:
        - name: Install httpd package
          yum: name=httpd1234 state=installed
          ignore_errors: yes
        - name: copy index.html
          copy: src=index.html dest=/var/www/html/index.html
        - name: start httpd service
          service: name=httpd state=started
