---
- hosts: server2
  user: test
  sudo: yes
  gather_facts: yes
  tasks:
       - name: Remove older version of tomcat
         file: path=/usr/local/tomcat state=absent 
       - name: download tomcat7
         get_url: url=http://redrockdigimark.com/apachemirror/tomcat/tomcat-8/v8.5.11/bin/apache-tomcat-8.5.11.tar.gz dest=/tmp
       - name: create tomcat dir
         command: mkdir /usr/local/tomcat
       - name: mv tar file to tomcat location
         command: chdir=/tmp /bin/mv apache-tomcat-8.5.11.tar.gz /usr/local/tomcat
       - name: extract tar file
         command: chdir=/usr/local/tomcat /bin/tar -xvzf apache-tomcat-8.5.11.tar.gz
       - name: start services
         command: nohup /usr/local/tomcat/apache-tomcat-8.5.11/bin/startup.sh &
         register: result
       - debug: var=result
